diff a/arch/arm/mach-msm/Makefile b/arch/arm/mach-msm/Makefile	(rejected hunks)
@@ -425,4 +425,6 @@ obj-$(CONFIG_PERFMAP) += perfmap.o
 
 obj-$(CONFIG_ARCH_MSM8974) += lge_moca_drv.o
 
+obj-$(CONFIG_FORCE_FAST_CHARGE) += fastchg.o
+
 obj-$(CONFIG_HAS_MACH_MEMUTILS) += memutils/
\ No newline at end of file
